require("nyg.plugins.nvim-tree")
require("nyg.plugins.telescope")
--require("core.plugins.theme")
--equire("core.plugins.lualine")
--equire("core.plugins.autopairs")
--require("core.plugins.treesitter")
-- lsp imports
--require("core.plugins.lsp.mason")
--require("core.plugins.lsp.nvim-cmp")
--require("core.plugins.lsp.completion")
--require("core.plugins.lsp.lspconfig")
--require("core.plugins.lsp.lspsaga")
